services:
  - type: web
    name: aura-livekit-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: LIVEKIT_API_KEY
        value: APIpwGekiRj6WSd
      - key: LIVEKIT_API_SECRET
        value: IXB2f9Qw3Ie8u2AA74rR4idWRMjVj2YPeIB3lveiUwID
      - key: LIVEKIT_URL
        value: wss://aura-oau79de6.livekit.cloud
      - key: PORT
        value: 10000
    autoDeploy: true